### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by jimjamdev** [bitcoinprivate/BitcoinPrivate#2]
You're basically calling another legit coin a scam, then trying to claim you came up with it first.
You also have 0 code.

Seriously man, I've seen some bad attempts, but this takes the biscuit.

**Comment by alph43oss** [comment]
When smoking crack meets crypto...

**Comment by bitcoinprivate** [comment]
Are you fucking serious?

Domain Name: BITCOINPRIVATE.COM  
Creation Date: 2014-08-09T21:37:50Z 

## `9 Sep, 2014.` Yes, at that time you didn't know what Bitcoin is.

Domain Name: BITCOINPRIVATE.ORG
Creation Date: 2016-09-01T21:44:14Z

## `1 Sep, 2016.`

Get out from here, scammer.

**Comment by jimmyjamieson** [comment]
Domain squatting has nothing to do with it being a legit project!

Maybe I'll go buy up bitcoinxxx.com then when someone start a project with the same name I'll try and claim it as mine. 

You're daft.

**Comment by jimjamdev** [comment]
Do you keep deleting comments because you're trying to hide something Mr Domain Squatter?
